export const LETTERS = Array.from('ABCDEFGHIJKLMNOPQRSTUVWXYZ')
export const MAX_LIVES = 11

export const LETTER_MODES = {
  AVAILABLE: Symbol('LETTER_MODES.AVAILABLE'),
  CORRECT: Symbol('LETTER_MODES.CORRECT'),
  INCORRECT: Symbol('LETTER_MODES.INCORRECT')
}

export const GAME_STATES = {
  CHOOSING_WORD: Symbol('CHOOSING_WORD'),
  IN_PROGRESS: Symbol('GAME_STATES.IN_PROGRESS'),
  GAME_OVER: Symbol('GAME_STATES.GAME_OVER')
}

export const OUTCOMES = {
  IN_PROGRESS: Symbol('OUTCOMES.IN_PROGRESS'),
  WON: Symbol('OUTCOMES.WON'),
  LOST: Symbol('OUTCOMES.LOST')
}
